### ISSUE TITLE
Suggestion -> Boat entity support

### ISSUE THREAD

**Issue by pjindras** [LaboCraft/Entity-Limiter#1]
Hello, it would be great, if it was possible to use the same logic to prevent boat lag machines like this one:

https://www.youtube.com/watch?v=BlkmrwqttJs&t=5s

**Comment by NathanFAIN** [comment]
Hi, thanks for your suggestion. 
I tried my best to support all entities : https://github.com/LaboCraft/Entity-Limiter/releases/tag/v2.0.0

Nathan
